services:
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql

  mock-server:
    image: stoplight/prism:4
    ports:
      - "4010:4010"
    volumes:
      - ./backend/openapi.yaml:/tmp/openapi.yaml
    command: mock -h 0.0.0.0 --cors /tmp/openapi.yaml

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./backend/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      URL: openapi.yaml

volumes:
  db-data:
