/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google 認証・JWT 発行
         * @description Google ID トークンを検証し、JWT アクセストークンを発行する。ユーザーが存在しない場合は自動作成する。
         */
        post: operations["authenticateWithGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 現在のユーザー取得
         * @description 認証済みユーザーの情報を取得する。
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        /**
         * アカウント削除
         * @description ユーザーと関連する全支出記録を削除する。
         */
        delete: operations["deleteCurrentUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * カテゴリ一覧取得
         * @description カテゴリの一覧を表示順で取得する。
         */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 支出一覧取得
         * @description フィルタ条件に基づいて支出一覧を返す。ソート順は date DESC, created_at DESC。
         */
        get: operations["listTransactions"];
        put?: never;
        /**
         * 支出登録
         * @description 新しい支出を登録する。
         */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 支出 ID */
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        /**
         * 支出詳細取得
         * @description 指定された ID の支出詳細を取得する。
         */
        get: operations["getTransaction"];
        /**
         * 支出更新
         * @description 支出を全項目置換で更新する。
         */
        put: operations["updateTransaction"];
        post?: never;
        /**
         * 支出削除
         * @description 指定された ID の支出を削除する。
         */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * カテゴリ別分析
         * @description 指定期間のカテゴリ別支出集計を返す。金額 0 のカテゴリは除外。金額降順でソート。
         */
        get: operations["getCategoryAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/need-want": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * NEED/WANT 分析
         * @description 指定期間の NEED/WANT/UNSET 別支出集計を返す。3 種類すべて常に含まれる。
         */
        get: operations["getNeedWantAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 支出の NEED/WANT 分類
         * @enum {string}
         */
        NeedWantType: "NEED" | "WANT" | "UNSET";
        /** @description OAuth2 認証リクエスト */
        AuthRequest: {
            /**
             * @description OAuth2 ID トークン
             * @example eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            id_token: string;
        };
        /** @description 支出登録・更新リクエスト */
        TransactionRequest: {
            /**
             * Format: date
             * @description 支出日（ISO 8601）
             * @example 2026-02-23
             */
            date: string;
            /**
             * @description 金額（数値を文字列型で精度を保持）
             * @example 1200
             */
            amount: string;
            /**
             * Format: int64
             * @description カテゴリ ID（省略時は「未分類」）
             * @example 1
             */
            category_id?: number;
            /** @description 分類（省略時は UNSET） */
            need_want_type?: components["schemas"]["NeedWantType"];
            /**
             * @description タイトル
             * @example ランチ
             */
            title?: string;
            /**
             * @description メモ
             * @example 同僚と渋谷のイタリアンへ
             */
            memo?: string;
        };
        /** @description 認証レスポンス */
        AuthResponse: {
            /**
             * @description JWT アクセストークン（24 時間有効）
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            access_token: string;
            user: components["schemas"]["UserResponse"];
        };
        /** @description ユーザー情報 */
        UserResponse: {
            /**
             * Format: int64
             * @description ユーザー ID
             * @example 1
             */
            id: number;
            /**
             * Format: email
             * @description メールアドレス
             * @example user@example.com
             */
            email: string;
            /**
             * @description 表示名
             * @example 山田太郎
             */
            display_name: string;
            /**
             * Format: date-time
             * @description アカウント作成日時
             * @example 2026-01-15T09:30:00Z
             */
            created_at: string;
        };
        /** @description カテゴリ */
        Category: {
            /**
             * Format: int64
             * @description カテゴリ ID
             * @example 1
             */
            id: number;
            /**
             * @description カテゴリ名
             * @example 食費
             */
            name: string;
            /**
             * @description 表示順（昇順）
             * @example 1
             */
            display_order: number;
        };
        /** @description カテゴリ一覧 */
        CategoryList: {
            /** @description カテゴリの配列 */
            items: components["schemas"]["Category"][];
        };
        /** @description 支出レコード */
        Transaction: {
            /**
             * Format: int64
             * @description 支出 ID
             * @example 1
             */
            id: number;
            /**
             * Format: date
             * @description 支出日
             * @example 2026-02-23
             */
            date: string;
            /**
             * @description 金額（数値を文字列型で精度を保持）
             * @example 1200
             */
            amount: string;
            /**
             * Format: int64
             * @description カテゴリ ID
             * @example 1
             */
            category_id: number;
            /**
             * @description カテゴリ名
             * @example 食費
             */
            category_name: string;
            /** @description NEED/WANT 分類 */
            need_want_type: components["schemas"]["NeedWantType"];
            /**
             * @description タイトル
             * @example ランチ
             */
            title?: string;
            /**
             * @description メモ
             * @example 同僚と渋谷のイタリアンへ
             */
            memo?: string;
            /**
             * Format: date-time
             * @description 作成日時
             * @example 2026-02-23T12:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description 更新日時
             * @example 2026-02-23T12:00:00Z
             */
            updated_at: string;
        };
        /** @description 支出一覧 */
        TransactionList: {
            /** @description 支出の配列 */
            items: components["schemas"]["Transaction"][];
        };
        /** @description カテゴリ別集計項目 */
        CategoryAnalyticsItem: {
            /**
             * Format: int64
             * @description カテゴリ ID
             * @example 1
             */
            category_id: number;
            /**
             * @description カテゴリ名
             * @example 食費
             */
            category_name: string;
            /**
             * @description カテゴリ別合計金額
             * @example 45000
             */
            amount: string;
            /**
             * @description 構成比（小数第 1 位）
             * @example 34.6
             */
            percentage: number;
            /**
             * @description 取引件数
             * @example 15
             */
            transaction_count: number;
        };
        /** @description カテゴリ別支出分析 */
        CategoryAnalytics: {
            /**
             * @description 全カテゴリの合計金額
             * @example 130000
             */
            total_amount: string;
            /** @description カテゴリ別集計（金額降順） */
            categories: components["schemas"]["CategoryAnalyticsItem"][];
        };
        /** @description NEED/WANT 別集計項目 */
        NeedWantBreakdownItem: {
            /** @description 分類タイプ */
            type: components["schemas"]["NeedWantType"];
            /**
             * @description 分類別合計金額
             * @example 80000
             */
            amount: string;
            /**
             * @description 構成比（小数第 1 位）
             * @example 61.5
             */
            percentage: number;
            /**
             * @description 取引件数
             * @example 20
             */
            transaction_count: number;
        };
        /** @description NEED/WANT 別支出分析 */
        NeedWantAnalytics: {
            /**
             * @description 全分類の合計金額
             * @example 130000
             */
            total_amount: string;
            /** @description NEED/WANT/UNSET の内訳（3 種類すべて含む） */
            breakdown: components["schemas"]["NeedWantBreakdownItem"][];
        };
        /** @description RFC 9457 Problem Details */
        ProblemDetail: {
            /**
             * @description エラー種別の URI
             * @example about:blank
             */
            type: string;
            /**
             * @description HTTP ステータスのフレーズ
             * @example Not Found
             */
            title: string;
            /**
             * @description HTTP ステータスコード
             * @example 404
             */
            status: number;
            /**
             * @description エラーの詳細メッセージ
             * @example Transaction with id 999 not found
             */
            detail?: string;
            /**
             * @description リクエスト URI
             * @example /api/v1/transactions/999
             */
            instance?: string;
        };
        /** @description バリデーションエラー詳細（RFC 9457 拡張） */
        ValidationProblemDetail: components["schemas"]["ProblemDetail"] & {
            /** @description フィールドごとのエラー一覧 */
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /**
             * @description エラーメッセージ
             * @example must not be null
             */
            detail: string;
            /**
             * @description JSON Pointer 形式のフィールドパス
             * @example #/amount
             */
            pointer: string;
        };
    };
    responses: {
        /** @description 認証が必要、またはトークンが無効・期限切れ */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description リクエスト不正（JSON パースエラー、不正なクエリパラメータ） */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description リソースが見つからない（他ユーザーのリソースも 404 を返す） */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description バリデーションエラー */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblemDetail"];
            };
        };
        /** @description 予期しないサーバーエラー */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        /** @description 支出 ID */
        TransactionId: number;
        /** @description 開始日（inclusive、ISO 8601） */
        DateFrom: string;
        /** @description 終了日（inclusive、ISO 8601） */
        DateTo: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authenticateWithGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRequest"];
            };
        };
        responses: {
            /** @description 認証成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description ID トークン検証失敗 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                /** @description 開始日（inclusive、ISO 8601） */
                from?: string;
                /** @description 終了日（inclusive、ISO 8601） */
                to?: string;
                /** @description カテゴリ ID（複数指定可） */
                category_id?: number[];
                /** @description NEED/WANT フィルタ */
                need_want_type?: components["schemas"]["NeedWantType"];
                /** @description タイトル・メモの部分一致検索 */
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description 作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 支出 ID */
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 支出 ID */
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 支出 ID */
                id: components["parameters"]["TransactionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCategoryAnalytics: {
        parameters: {
            query?: {
                /** @description 開始日（inclusive、ISO 8601） */
                from?: components["parameters"]["DateFrom"];
                /** @description 終了日（inclusive、ISO 8601） */
                to?: components["parameters"]["DateTo"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryAnalytics"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getNeedWantAnalytics: {
        parameters: {
            query?: {
                /** @description 開始日（inclusive、ISO 8601） */
                from?: components["parameters"]["DateFrom"];
                /** @description 終了日（inclusive、ISO 8601） */
                to?: components["parameters"]["DateTo"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedWantAnalytics"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
